In [2]:
import numpy as np

In [9]:
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

arr2 = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr2)

zeros_arr = np.zeros((2, 3))
print("Zeros Array:\n", zeros_arr)

ones_arr = np.ones((2, 3))
print("Ones Array:\n", ones_arr)

full = np.full((4,2),5)
print("Full array \n",full)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2]
 [3 4]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array 
 [[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [14]:
random_arr = np.random.rand(2, 2)
print("Random Array:\n", random_arr)

arange_arr = np.arange(0, 10, 2)
print("Arange Array:", arange_arr)

reshaped = np.arange(12).reshape(3, 4)
print("Reshaped Array (3x4):\n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array:", flattened)

transpose = arr2.T
print("Transpose:\n", transpose)

Random Array:
 [[0.02853337 0.60397351]
 [0.92371583 0.63265353]]
Arange Array: [0 2 4 6 8]
Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
 [[1 3]
 [2 4]]


In [19]:
sorted_arr = np.sort(arr1)
print("Sorted Array:", sorted_arr)

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Basic Slicing:",arr[2:7])
print("Negative Slicing:",arr[-3])

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print("Concatenated Array:",combined)

mean_val = np.mean(arr1)
print("Mean:", mean_val)

print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

Sorted Array: [1 2 3]
Basic Slicing: [3 4 5 6 7]
Negative Slicing: 10
Concatenated Array: [1 2 3 4 5 6]
Mean: 2.0
Max: 3
Min: 1
